### ISSUE TITLE
Gradle Build dependency

### ISSUE THREAD

**Issue by erwandy92** [pollux-/DualProgressBar#2]
Hello, Kumar.

Thank you very much for creating such a great progress animation.
I'm wondering whether you have made the Gradle dependency open for the public to use?

Thanks in advance.

**Comment by pollux-** [comment]
I just pushed to Jcenter() 🍺 Will update you once it is up. Thanks for using it 👍

**Comment by pollux-** [comment]
@erwandy92 done
