### ISSUE TITLE
Include project license in top level of repo

### ISSUE THREAD

**Issue by kylethebaker** [pollux-/DualProgressBar#3]
Currently the only mention of a license is in the `build.gradle` here: https://github.com/pollux-/DualProgressBar/blob/f4347ddf6cc6bcc88c06d3ab63d36b3ee249b6fb/dualprogressview/build.gradle#L54

It's somewhat ambiguous (imo) if this applies to all of the code. Regardless, it requires some hunting down to find. I think there should be a canonical `LICENSE.md` in the root of the repo so it's clear what the license is.

**Comment by pollux-** [comment]
@kylethebaker done
